license upload
deneb-alpha/Lab_open_source pull request #19
Opened 2023-12-20 16:07 UTC by Meuritz

2023-12-28 14:51 UTC, deneb-alpha requested changes
Ciao @Meuritz ,
potresti inviare due PR distinte?

di solito una PR è "a tema" ma in questo caso stai inviando gli appunti e anche la licenza. 
In aggiunta, la PR ha un titolo e una descrizione che lasciano pensare solo che la modifica riguardi solo la licenza.

Per quanto riguarda la licenza scelta, i andrebbe anche di spiegare nella descrizione della PR come mai hai scelto questa specifica licenza?

Grazie ancora!

2024-01-02 12:18 UTC, Meuritz commented
Ora cambio anche la licenza, dato che non è codice non ha molto senso usare quella che ho mandato (secondo me), per quanto riguarda la PR pensavo di fare un commit con fonti, ed uno sul ragionamento che c'è dietro, ma per quanto riguarda la presentazione in ser per se, la linko oppure faccio una pull request ?

2024-01-02 12:42 UTC, Meuritz commented
lo cambiata ma avevo messo aggiorna prima di farlo, errore mio

2024-01-14 18:49 UTC, deneb-alpha commented
> Avevo la motivazione in testa ma non lo scritta provvedo, mente per quanto riguarda la PR pensavo di fare un commit con le fonti, ed uno sul ragionamento che c'è dietro, ma per quanto riguarda la presentazione in ser per se, la linko oppure faccio una pull request ?

Per la presentazione da utilizzare all'esame farei comunque una nuova PR.

Questa ha commit differenti che caricano il file della licenza e i tuoi appunti.
Se vuoi mantenere tutto insieme in questa PR dovresti almeno rinominare il titolo di questa PR e aggiungere le informazioni alla descrizione.

Al momento la descrizione è vuota e il titolo è `license upload` mentre la tua PR fornisce anche alcuni degli appunti che hai preso sui comandi git

2024-01-17 09:54 UTC, closed without merging